import {ToDo, List} from '../components/14passAnArrayAsProps';
// The date prop of the CurrentDate should contain a string of text.

// The date prop should be generated by calling Date()

// The CurrentDate component should render the value from the date prop in the p tag.


describe('Pass Array As Props', () => {

    let wrapperToDo;
    let wrapperList;

    beforeEach(() => {
        wrapperToDo = shallow(<ToDo />);
        wrapperList = shallow(<List />)

   });

    it('The Calendar component should return a single div element.', () => {  
        expect(wrapperToDo.at(0).exists('div')).toBe(true)     
    });

    // it('The second child of the Calendar component should be the CurrentDate component.', ()=>{
    //     expect(wrapperCalendar.children(0).at(1).exists('CurrentDate')).toBe(true)
    
    //     // console.log(wrapperCalendar.debug())
    //     // expect(wrapperCalendar.find('CurrentDate'))
    // })
});